# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1fed22f1c06fe4ec54d23b809153f410341ee0c87b6315d3cf1ac5b347001f548d6c150cc1dc3691fe1c0de5f98c24d34c08baaaff07fd06a78812591435e40

test:
  secret_key_base: f3c7e69e2f25551eefc0f7cc65f1081ff21400b612d7cab8533288c9f39d4697e5ede7719a357b127ec77b82b40c20dbad7982efdc21086155c6dd24cae82d90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
